load("@rules_android//android:rules.bzl", "android_binary", "android_library")

android_binary(
    name = "android_app",
    manifest = "AndroidManifest.xml",
    srcs = [
        "src/main/java/com/eazzyapps/example/android/MainActivity.kt"
    ]
)