// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.Picking.Api.Data;

namespace Warehouse.Picking.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210521103422_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Warehouse.Picking.Api.Data.Models.DbArticle", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gtin")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "NoteId");

                    b.ToTable("articles");
                });

            modelBuilder.Entity("Warehouse.Picking.Api.Data.Models.DbArticle", b =>
                {
                    b.OwnsOne("Warehouse.Picking.Api.Data.Models.DbArticleBundle", "Bundle", b1 =>
                        {
                            b1.Property<int>("DbArticleId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("DbArticleNoteId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.HasKey("DbArticleId", "DbArticleNoteId");

                            b1.ToTable("articles");

                            b1.WithOwner()
                                .HasForeignKey("DbArticleId", "DbArticleNoteId");
                        });

                    b.OwnsOne("Warehouse.Picking.Api.Data.Models.DbArticleQuantity", "Quantity", b1 =>
                        {
                            b1.Property<int>("DbArticleId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("DbArticleNoteId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Expected")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Processed")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DbArticleId", "DbArticleNoteId");

                            b1.ToTable("articles");

                            b1.WithOwner()
                                .HasForeignKey("DbArticleId", "DbArticleNoteId");
                        });

                    b.Navigation("Bundle");

                    b.Navigation("Quantity");
                });
#pragma warning restore 612, 618
        }
    }
}
